### ISSUE TITLE
e2e infrastructure needs for CloudEvent sink for Azure Event Grid

### ISSUE THREAD

**Issue by tomkerkhove** [kedacore/testing-infrastructure#144]
With regards to the e2e infrastructure for CloudEvent sink for Azure Event Grid, what we will need to add is:

- An Azure Event Grid Topic to which we will push events
- An Azure Service Bus Namespace + Topic that is used to subscribe to events, from the above Azure Event Grid Topic.

Relates to https://github.com/kedacore/keda/issues/3587

**Comment by JorTurFer** [comment]
done!

**Comment by JorTurFer** [comment]
https://github.com/kedacore/testing-infrastructure/actions/runs/8412383836/job/23033171611
